export interface Product {
  id: string
  name: string
  price: number
  image: string
  description: string
  category: string
}

export const products: Product[] = [
  // Accessories
  {
    id: "acc1",
    name: "Elegant Wristwatch",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Wristwatch",
    description: "A sophisticated timepiece that combines style and functionality.",
    category: "Accessories",
  },
  {
    id: "acc2",
    name: "Leather Laptop Bag",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300&text=Laptop+Bag",
    description: "A durable and stylish laptop bag made from genuine leather.",
    category: "Accessories",
  },
  {
    id: "acc3",
    name: "Sunglasses",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300&text=Sunglasses",
    description: "Stylish sunglasses with UV protection.",
    category: "Accessories",
  },
  {
    id: "acc4",
    name: "Leather Wallet",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Wallet",
    description: "A slim, genuine leather wallet with multiple card slots.",
    category: "Accessories",
  },
  {
    id: "acc5",
    name: "Silk Scarf",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Scarf",
    description: "A luxurious silk scarf with a beautiful print.",
    category: "Accessories",
  },
  {
    id: "acc6",
    name: "Baseball Cap",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300&text=Baseball+Cap",
    description: "A classic baseball cap with adjustable strap.",
    category: "Accessories",
  },
  {
    id: "acc7",
    name: "Backpack",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Backpack",
    description: "A durable backpack with multiple compartments.",
    category: "Accessories",
  },
  {
    id: "acc8",
    name: "Belt",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Belt",
    description: "A stylish leather belt with a classic buckle.",
    category: "Accessories",
  },
  {
    id: "acc9",
    name: "Gloves",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Gloves",
    description: "Warm and comfortable gloves for cold weather.",
    category: "Accessories",
  },
  {
    id: "acc10",
    name: "Hat",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300&text=Hat",
    description: "A stylish hat to protect you from the sun.",
    category: "Accessories",
  },
  {
    id: "acc11",
    name: "Scarf",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Scarf",
    description: "A warm and cozy scarf for cold weather.",
    category: "Accessories",
  },
  {
    id: "acc12",
    name: "Socks",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300&text=Socks",
    description: "Comfortable socks for everyday wear.",
    category: "Accessories",
  },
  {
    id: "acc13",
    name: "Tie",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Tie",
    description: "A stylish tie for formal occasions.",
    category: "Accessories",
  },
  {
    id: "acc14",
    name: "Umbrella",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300&text=Umbrella",
    description: "A durable umbrella to protect you from the rain.",
    category: "Accessories",
  },
  {
    id: "acc15",
    name: "Watch",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Watch",
    description: "A stylish watch for everyday wear.",
    category: "Accessories",
  },
  {
    id: "acc16",
    name: "Wristband",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300&text=Wristband",
    description: "A stylish wristband for everyday wear.",
    category: "Accessories",
  },
  {
    id: "acc17",
    name: "Sunglasses",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300&text=Sunglasses",
    description: "Stylish sunglasses with UV protection.",
    category: "Accessories",
  },
  {
    id: "acc18",
    name: "Bag",
    price: 69.99,
    image: "/placeholder.svg?height=300&width=300&text=Bag",
    description: "A stylish bag for everyday wear.",
    category: "Accessories",
  },
  {
    id: "acc19",
    name: "Purse",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Purse",
    description: "A stylish purse for everyday wear.",
    category: "Accessories",
  },
  {
    id: "acc20",
    name: "Wallet",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Wallet",
    description: "A stylish wallet for everyday wear.",
    category: "Accessories",
  },

  // Electronics
  {
    id: "elec1",
    name: "Wireless Earbuds",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300&text=Earbuds",
    description: "High-quality wireless earbuds with noise-cancellation technology.",
    category: "Electronics",
  },
  {
    id: "elec2",
    name: "Smart Home Hub",
    price: 149.99,
    image: "/placeholder.svg?height=300&width=300&text=Smart+Hub",
    description: "Control your smart home devices with ease using this intuitive hub.",
    category: "Electronics",
  },
  {
    id: "elec3",
    name: "Bluetooth Speaker",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Speaker",
    description: "A portable Bluetooth speaker with excellent sound quality.",
    category: "Electronics",
  },
  {
    id: "elec4",
    name: "Fitness Tracker",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Fitness+Tracker",
    description: "Track your fitness goals with this advanced wearable device.",
    category: "Electronics",
  },
  {
    id: "elec5",
    name: "Wireless Charging Pad",
    price: 34.99,
    image: "/placeholder.svg?height=300&width=300&text=Charging+Pad",
    description: "A sleek wireless charging pad compatible with all Qi-enabled devices.",
    category: "Electronics",
  },
  {
    id: "elec6",
    name: "Smartwatch",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Smartwatch",
    description: "A smartwatch with various features.",
    category: "Electronics",
  },
  {
    id: "elec7",
    name: "Headphones",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Headphones",
    description: "High-quality headphones with noise-cancellation technology.",
    category: "Electronics",
  },
  {
    id: "elec8",
    name: "Tablet",
    price: 299.99,
    image: "/placeholder.svg?height=300&width=300&text=Tablet",
    description: "A tablet with a large screen and powerful processor.",
    category: "Electronics",
  },
  {
    id: "elec9",
    name: "Laptop",
    price: 999.99,
    image: "/placeholder.svg?height=300&width=300&text=Laptop",
    description: "A powerful laptop for work and play.",
    category: "Electronics",
  },
  {
    id: "elec10",
    name: "Desktop Computer",
    price: 1299.99,
    image: "/placeholder.svg?height=300&width=300&text=Desktop+Computer",
    description: "A powerful desktop computer for work and play.",
    category: "Electronics",
  },
  {
    id: "elec11",
    name: "TV",
    price: 499.99,
    image: "/placeholder.svg?height=300&width=300&text=TV",
    description: "A large TV with a high resolution.",
    category: "Electronics",
  },
  {
    id: "elec12",
    name: "Camera",
    price: 299.99,
    image: "/placeholder.svg?height=300&width=300&text=Camera",
    description: "A high-quality camera for taking photos and videos.",
    category: "Electronics",
  },
  {
    id: "elec13",
    name: "Video Game Console",
    price: 299.99,
    image: "/placeholder.svg?height=300&width=300&text=Video+Game+Console",
    description: "A video game console with various games.",
    category: "Electronics",
  },
  {
    id: "elec14",
    name: "Remote Control",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Remote+Control",
    description: "A remote control for your TV.",
    category: "Electronics",
  },
  {
    id: "elec15",
    name: "Power Bank",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Power+Bank",
    description: "A power bank to charge your devices on the go.",
    category: "Electronics",
  },
  {
    id: "elec16",
    name: "Keyboard",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Keyboard",
    description: "A keyboard for your computer.",
    category: "Electronics",
  },
  {
    id: "elec17",
    name: "Mouse",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Mouse",
    description: "A mouse for your computer.",
    category: "Electronics",
  },
  {
    id: "elec18",
    name: "Webcam",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Webcam",
    description: "A webcam for your computer.",
    category: "Electronics",
  },
  {
    id: "elec19",
    name: "Monitor",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Monitor",
    description: "A monitor for your computer.",
    category: "Electronics",
  },
  {
    id: "elec20",
    name: "Printer",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Printer",
    description: "A printer for your computer.",
    category: "Electronics",
  },

  // Clothing
  {
    id: "cloth1",
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=T-Shirt",
    description: "A comfortable and eco-friendly t-shirt made from 100% organic cotton.",
    category: "Clothing",
  },
  {
    id: "cloth2",
    name: "Denim Jeans",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300&text=Jeans",
    description: "Classic denim jeans with a comfortable fit.",
    category: "Clothing",
  },
  {
    id: "cloth3",
    name: "Wool Sweater",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Sweater",
    description: "A warm and cozy wool sweater perfect for cold weather.",
    category: "Clothing",
  },
  {
    id: "cloth4",
    name: "Summer Dress",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Dress",
    description: "A light and breezy summer dress with a floral pattern.",
    category: "Clothing",
  },
  {
    id: "cloth5",
    name: "Leather Jacket",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Leather+Jacket",
    description: "A stylish leather jacket for a timeless look.",
    category: "Clothing",
  },
  {
    id: "cloth6",
    name: "T-Shirt",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=T-Shirt",
    description: "A comfortable t-shirt for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth7",
    name: "Shirt",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Shirt",
    description: "A comfortable shirt for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth8",
    name: "Pants",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Pants",
    description: "Comfortable pants for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth9",
    name: "Shorts",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300&text=Shorts",
    description: "Comfortable shorts for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth10",
    name: "Skirt",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Skirt",
    description: "A stylish skirt for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth11",
    name: "Dress",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300&text=Dress",
    description: "A stylish dress for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth12",
    name: "Coat",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Coat",
    description: "A warm coat for cold weather.",
    category: "Clothing",
  },
  {
    id: "cloth13",
    name: "Jacket",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Jacket",
    description: "A stylish jacket for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth14",
    name: "Sweater",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Sweater",
    description: "A warm sweater for cold weather.",
    category: "Clothing",
  },
  {
    id: "cloth15",
    name: "Hoodie",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Hoodie",
    description: "A comfortable hoodie for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth16",
    name: "Shoes",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Shoes",
    description: "Comfortable shoes for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth17",
    name: "Boots",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Boots",
    description: "Warm boots for cold weather.",
    category: "Clothing",
  },
  {
    id: "cloth18",
    name: "Sandals",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Sandals",
    description: "Comfortable sandals for warm weather.",
    category: "Clothing",
  },
  {
    id: "cloth19",
    name: "Sneakers",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300&text=Sneakers",
    description: "Comfortable sneakers for everyday wear.",
    category: "Clothing",
  },
  {
    id: "cloth20",
    name: "Flip-Flops",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300&text=Flip-Flops",
    description: "Comfortable flip-flops for warm weather.",
    category: "Clothing",
  },

  // Fitness
  {
    id: "fit1",
    name: "Yoga Mat",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Yoga+Mat",
    description: "A non-slip, eco-friendly yoga mat perfect for your daily practice.",
    category: "Fitness",
  },
  {
    id: "fit2",
    name: "Resistance Bands Set",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Resistance+Bands",
    description: "A set of resistance bands for versatile strength training.",
    category: "Fitness",
  },
  {
    id: "fit3",
    name: "Adjustable Dumbbells",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Dumbbells",
    description: "Space-saving adjustable dumbbells for home workouts.",
    category: "Fitness",
  },
  {
    id: "fit4",
    name: "Foam Roller",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300&text=Foam+Roller",
    description: "A foam roller for muscle recovery and flexibility.",
    category: "Fitness",
  },
  {
    id: "fit5",
    name: "Jump Rope",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300&text=Jump+Rope",
    description: "A high-quality jump rope for cardio workouts.",
    category: "Fitness",
  },
  {
    id: "fit6",
    name: "Exercise Ball",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Exercise+Ball",
    description: "An exercise ball for core strengthening and balance.",
    category: "Fitness",
  },
  {
    id: "fit7",
    name: "Yoga Block",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300&text=Yoga+Block",
    description: "A yoga block for support during yoga practice.",
    category: "Fitness",
  },
  {
    id: "fit8",
    name: "Yoga Strap",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Yoga+Strap",
    description: "A yoga strap for increased flexibility.",
    category: "Fitness",
  },
  {
    id: "fit9",
    name: "Fitness Tracker",
    price: 99.99,
    image: "/placeholder.svg?height=300&width=300&text=Fitness+Tracker",
    description: "A fitness tracker to monitor your activity.",
    category: "Fitness",
  },
  {
    id: "fit10",
    name: "Heart Rate Monitor",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Heart+Rate+Monitor",
    description: "A heart rate monitor to track your heart rate.",
    category: "Fitness",
  },
  {
    id: "fit11",
    name: "Smartwatch",
    price: 149.99,
    image: "/placeholder.svg?height=300&width=300&text=Smartwatch",
    description: "A smartwatch with fitness tracking capabilities.",
    category: "Fitness",
  },
  {
    id: "fit12",
    name: "Running Shoes",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300&text=Running+Shoes",
    description: "Running shoes for comfort and support.",
    category: "Fitness",
  },
  {
    id: "fit13",
    name: "Workout Clothes",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Workout+Clothes",
    description: "Workout clothes for comfort and performance.",
    category: "Fitness",
  },
  {
    id: "fit14",
    name: "Water Bottle",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Water+Bottle",
    description: "A water bottle to stay hydrated during workouts.",
    category: "Fitness",
  },
  {
    id: "fit15",
    name: "Towel",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300&text=Towel",
    description: "A towel to wipe sweat during workouts.",
    category: "Fitness",
  },
  {
    id: "fit16",
    name: "Gym Bag",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Gym+Bag",
    description: "A gym bag to carry your workout gear.",
    category: "Fitness",
  },
  {
    id: "fit17",
    name: "Headphones",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300&text=Headphones",
    description: "Headphones to listen to music during workouts.",
    category: "Fitness",
  },
  {
    id: "fit18",
    name: "Fitness Tracker",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Fitness+Tracker",
    description: "A fitness tracker to monitor your activity.",
    category: "Fitness",
  },
  {
    id: "fit19",
    name: "Smartwatch",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300&text=Smartwatch",
    description: "A smartwatch with fitness tracking capabilities.",
    category: "Fitness",
  },
  {
    id: "fit20",
    name: "Workout Gloves",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Workout+Gloves",
    description: "Workout gloves to protect your hands.",
    category: "Fitness",
  },
]

export const categories = Array.from(new Set(products.map((product) => product.category)))

